### PR TITLE
Utilities

### PR DESCRIPTION
**Pull request by TheBunnyMan123**
@PoolloverNathan please port nano and/or vi to this

### CODE REVIEW

**Comment by PoolloverNathan** [comment]
idk CC api well enough to nano/vim; is a stripped-down ed enough? CC uses standard `io.read`/`io.write`, right?

**Review by PoolloverNathan — CHANGES_REQUESTED** [review]
holding this until an editor is implemented, as requested

**Comment by TheBunnyMan123** [comment]
it doesn't need to be a good editor, it just needs to support read and write, and maybe TAB for in-game editing

**Comment by TheBunnyMan123** [comment]
also I would prefer if this wasn't held as it also makes some necessary changes to shell api

**Review by PoolloverNathan — APPROVED** [review]
lgtm (didn't read code)

**Pull request merged**
