### PR TITLE
term api

### PR DESCRIPTION
**Pull request by TheBunnyMan123**

### CODE REVIEW

**Comment by TheBunnyMan123** [comment]
monitor functionality is broken now

**Comment by TheBunnyMan123** [comment]
eval doesn't use overridden functions, this should also be fixed

**Comment by TheBunnyMan123** [comment]
Everything (except eval) is working now, we can fix eval later, but this is overall ready

**Comment by TheBunnyMan123** [comment]
DON'T MERGE THIS I AM ADDING NESTED SHELLS

**Review by PoolloverNathan — CHANGES_REQUESTED** [review]
style: define foo:bar() instead of foo.bar(self)

**Comment by TheBunnyMan123** [comment]
style: no

**Review by PoolloverNathan — APPROVED** [review]
style: point taken

**Review by PoolloverNathan — APPROVED** [review]

**Pull request merged**
