### PR TITLE
Even more utils

### PR DESCRIPTION
**Pull request by PoolloverNathan**
Adds:
* `cupholder`
  ejects drives by name, all by default
* `aud`
  lists, starts, or stops music disks

### CODE REVIEW

**Review by TheBunnyMan123 — CHANGES_REQUESTED** [review]
maybe don't add the password file (how did you even do that on acident, I have a gitignore in place)

**Review by TheBunnyMan123 — CHANGES_REQUESTED** [review]
looks good. assuming you tested. please use 4 space tabs

**Comment by PoolloverNathan** [comment]
> looks good. assuming you tested. please use 4 space tabs

@TheBunnyMan123 tabs but they render 4 characters wide, or 4 physical spaces per indent?

**Review by TheBunnyMan123 — APPROVED** [review]
Cool :+1:

**Pull request merged**
